name: ✨ Feature Request
description: Suggest a new feature or enhancement for News MCP
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have considered if this could be solved with existing features
          required: true
        - label: This feature would benefit other users, not just myself
          required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: In one sentence, what feature would you like?
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New API endpoint
        - User Interface enhancement
        - RSS processing improvement
        - AI analysis feature
        - Performance optimization
        - Integration with external service
        - Configuration/deployment improvement
        - Developer experience improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        Include details about:
        - How it should work
        - What the user experience should be
        - Any technical considerations
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical/blocking
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change or addition
        - Medium - Moderate development effort
        - Complex - Significant development work
        - Major - Large feature requiring design phase
        - Unknown - Not sure about complexity
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. When [situation], I need [capability] because [reason]
        3. ...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples
      placeholder: |
        - Screenshots from other applications
        - Wireframes or sketches
        - API examples
        - Configuration examples

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation ideas
      placeholder: |
        - Database schema changes needed
        - API design considerations
        - Performance implications
        - Security considerations
        - Compatibility requirements

  - type: checkboxes
    id: implementation-areas
    attributes:
      label: Implementation Areas
      description: Which parts of the system would this feature likely affect?
      options:
        - label: Backend API
        - label: Frontend/Web UI
        - label: Database schema
        - label: RSS processing
        - label: AI analysis
        - label: Configuration
        - label: Documentation
        - label: Testing
        - label: Deployment/Docker

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, examples, or information
      placeholder: |
        - Links to similar features in other tools
        - Research or documentation
        - Related issues or discussions
        - Timeline considerations