name: Generate Database Documentation

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  schedule:
    - cron: '0 2 * * *'  # Nightly at 2 AM UTC
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: news_user
          POSTGRES_PASSWORD: news_password
          POSTGRES_DB: news_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install alembic sqlalchemy psycopg2-binary
          pip install -r requirements.txt

      - name: Run Alembic migrations
        env:
          DATABASE_URL: postgresql://news_user:news_password@localhost:5432/news_db
        run: |
          alembic upgrade head

      - name: Run SchemaSpy
        run: |
          docker run -v "$PWD/schemaspy-output:/output" \
            --network host \
            schemaspy/schemaspy:latest \
            -t pgsql \
            -host localhost \
            -port 5432 \
            -db news_db \
            -u news_user \
            -p news_password \
            -o /output \
            -s public \
            -vizjs

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: database-documentation
          path: schemaspy-output/

      - name: Deploy to GitHub Pages (on tags)
        if: startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./schemaspy-output
          destination_dir: db-docs/${{ github.ref_name }}

      - name: Deploy to GitHub Pages (latest)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./schemaspy-output
          destination_dir: db-docs/latest